import './globals.css';
import { UserProvider } from './context/UserContext';

export const metadata = {
  title: 'Lore Voice App',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
  return (
    <UserProvider>
      <html lang="pt-BR">
        <body>{children}</body>
      </html>
    </UserProvider>
  )
}
